name: Android CI on Push and PR to Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle 4.9
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "4.9"

      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3
      #   with:
      #     cmdline-tools-version: 9123335

      - name: Prepare
        # working-directory: ./VirtualApp
        run: |
          # echo "android.useAndroidX=true" >> gradle.properties
          gradle tasks
          gradle dependencies


      - name: Build with Gradle
        # working-directory: ./VirtualApp
        run: |
          gradle build
